version: '3'

services:
  laravel:
    build: ./php
    restart: always
    container_name: laravel_container
    ports:
      - '80:80'
    volumes:
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./src:/var/www/html
 
  db:
    image: mariadb
    restart: always
    container_name: mariadb_container
    ports:
      - '3306:3306'
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_USER: test
      MYSQL_PASSWORD: testpass
      MYSQL_DATABASE: test_db
      TZ: 'Asia/Tokyo'
    
  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: phpmyadmin_container
    ports:
      - '3000:80'
    volumes:
      - ./phpmyadmin/sessions:/sessions
    environment:
      - PMA_HOSTS=db
      - PMA_USER=root
      - PMA_PASSWORD=rootpass
    depends_on:
      - db
  
volumes:
  db_data:
